<?php

namespace App\Observers;

use App\Models\PpdbUser;
use Illuminate\Support\Facades\Mail;
use App\Mail\PpdbUserCreated;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class PpdbUserObserver
{
    /**
     * Handle the PpdbUser "created" event.
     */
    public function created(PpdbUser $ppdbUser): void
    {
        // Mail::to($ppdbUser->email)->send(new PpdbUserCreated($ppdbUser));
        Log::info($ppdbUser);
        try {
            $response_wa = Http::post(env('WHATSAPP_API_URL')  . "/send-message", [
                'session' => env('WHATSAPP_API_SESSION'),
                'to' => whatsappNumber($ppdbUser->whatsapp_number),
                'text' => "Terima Kasih Telah Mendaftar PPDB MAN 1 Padang Panjang. Data Anda Telah Terekam Dalam Sistem Kami, setelah itu silahkan login dan memilih Jalur pendaftaran yang diinginkan. \n \n" .
                    "Jika ada pertanyaan, silakan hubungi kami melalui WhatsApp atau email. \n" .
                    "Terima kasih, \n" .
                    "*Panitia PPDB* \n \n" .

                    "_generated by System_" . "\n" .
                    "https://ppdb.man1kotapadangpanjang.sch.id"
            ]);

            if ($response_wa->status() != 200) {
                Log::error('Failed to send message to ' . $ppdbUser->whatsapp_number);
            } else {
                Log::info('Message sent to ' . $ppdbUser->whatsapp_number);
            }
        } catch (\Exception $e) {
            Log::error($e->getMessage());
        }
    }

    /**
     * Handle the PpdbUser "updated" event.
     */
    public function updated(PpdbUser $ppdbUser): void
    {
        //
    }

    /**
     * Handle the PpdbUser "deleted" event.
     */
    public function deleted(PpdbUser $ppdbUser): void
    {
        //
    }

    /**
     * Handle the PpdbUser "restored" event.
     */
    public function restored(PpdbUser $ppdbUser): void
    {
        //
    }

    /**
     * Handle the PpdbUser "force deleted" event.
     */
    public function forceDeleted(PpdbUser $ppdbUser): void
    {
        //
    }
}
