<?php

namespace App\Observers;

use App\Models\PpdbRegistrationUser;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class PpdbRegistrationUserObserver
{
    /**
     * Handle the PpdbRegistrationUser "created" event.
     */
    public function created(PpdbRegistrationUser $ppdbRegistrationUser): void
    {
        Log::info($ppdbRegistrationUser);
        try {
            $response_wa = Http::post(env('WHATSAPP_API_URL')  . "/send-message", [
                'session' => env('WHATSAPP_API_SESSION'),
                'to' => whatsappNumber($ppdbRegistrationUser->user?->whatsapp_number),
                'text' => "Anda telah memilih jalur pendaftaran " . $ppdbRegistrationUser->path->name . ". T.A. " . $ppdbRegistrationUser->path->schoolYear->start_year . "/" . $ppdbRegistrationUser->path->schoolYear->end_year . ". data anda akan di verifikasi oleh panitia PPDB, jangan lupa untuk melihat info pendaftaran anda di website ini. \n \n" .
                    "Jika ada pertanyaan, silakan hubungi kami melalui WhatsApp atau email. \n" .
                    "Terima kasih, \n" .
                    "*Panitia PPDB* \n \n" .

                    "_generated by System_" . "\n" .
                    "https://ppdb.man1kotapadangpanjang.sch.id"
            ]);

            if ($response_wa->status() != 200) {
                Log::error('Failed to send message to ' . $ppdbRegistrationUser->user?->whatsapp_number);
            } else {
                Log::info('Message sent to ' . $ppdbRegistrationUser->user?->whatsapp_number);
            }
        } catch (\Exception $e) {
            Log::error($e->getMessage());
        }
    }

    /**
     * Handle the PpdbRegistrationUser "updated" event.
     */
    public function updated(PpdbRegistrationUser $ppdbRegistrationUser): void
    {
        Log::info($ppdbRegistrationUser);
        try {
            $response_wa = Http::post(env('WHATSAPP_API_URL')  . "/send-message", [
                'session' => env('WHATSAPP_API_SESSION'),
                'to' => whatsappNumber($ppdbRegistrationUser->user?->whatsapp_number),
                'text' => "Status anda telah diperbarui silahkan Cek status pendaftaran anda di website https://ppdb.man1kotapadangpanjang.sch.id. \n \n" .
                    "Tanggapan dari panitia PPDB: _" . $ppdbRegistrationUser->reason . "_\n \n" .
                    "Jika ada pertanyaan, silakan hubungi kami melalui WhatsApp atau email. \n" .
                    "Terima kasih, \n" .
                    "*Panitia PPDB* \n \n" .

                    "_generated by System_" . "\n" .
                    "https://ppdb.man1kotapadangpanjang.sch.id"
            ]);

            if ($response_wa->status() != 200) {
                Log::error('Failed to send message to ' . $ppdbRegistrationUser->user?->whatsapp_number);
            } else {
                Log::info('Message sent to ' . $ppdbRegistrationUser->user?->whatsapp_number);
            }
        } catch (\Exception $e) {
            Log::error($e->getMessage());
        }
    }

    /**
     * Handle the PpdbRegistrationUser "deleted" event.
     */
    public function deleted(PpdbRegistrationUser $ppdbRegistrationUser): void
    {
        //
    }

    /**
     * Handle the PpdbRegistrationUser "restored" event.
     */
    public function restored(PpdbRegistrationUser $ppdbRegistrationUser): void
    {
        //
    }

    /**
     * Handle the PpdbRegistrationUser "force deleted" event.
     */
    public function forceDeleted(PpdbRegistrationUser $ppdbRegistrationUser): void
    {
        //
    }
}
